apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sign-workflow-template
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: docker-login-and-sign
            template: docker-login-and-sign
        - - name: verify
            template: verify
            dependencies:
              - docker-login-and-sign

    - name: docker-login-and-sign
      container:
        image: docker:dind
        command: [sh, -c]
        args:
          - |
            apk add --no-cache cosign
            dockerd &
            sleep 5
            echo "Authenticating with Docker Hub"
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            echo "Signing the Docker image"
            COSIGN_DOCKER_MEDIA_TYPES=1 cosign sign --yes tbpatil19/breastcancerclassifier:version1.0
        env:
          - name: DOCKER_USERNAME
            valueFrom:
              secretKeyRef:
                name: docker-config
                key: username
          - name: DOCKER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: docker-config
                key: password
        securityContext:
          privileged: true
        volumeMounts:
          - name: docker-config
            mountPath: /root/.docker/config.json
            subPath: config.json
            readOnly: true
          - name: dind-storage
            mountPath: /var/lib/docker

    - name: verify
      container:
        image: bitnami/cosign:latest
        command: [sh, -c]
        args:
          - |
            echo "Verifying the signed image"
            cosign verify --certificate-identity toniya.lnu@acceldata.io --certificate-oidc-issuer https://accounts.google.com tbpatil19/breastcancerclassifier:version1.0
        volumeMounts:
          - name: cosign-pub
            mountPath: /etc/cosign
        env:
          - name: COSIGN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cosign-secret
                key: password
